"""empty message

Revision ID: 665dc38c52ab
Revises: 
Create Date: 2019-09-19 15:30:36.995073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665dc38c52ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_file', sa.String(length=140), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('trainLoss', sa.Float(), nullable=False),
    sa.Column('trainAcc', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('imageFilename', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('accessibility', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('dest_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('age_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['age_id'], ['age.id'], ),
    sa.ForeignKeyConstraint(['dest_id'], ['dest.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('type')
    op.drop_table('time')
    op.drop_table('dest')
    op.drop_table('demo')
    op.drop_table('age')
    # ### end Alembic commands ###
